name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the pipeline on pull requests to the main branch

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies for the backend
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install
      
      # Ensure Jest is installed globally
      - name: Install Jest globally
        run: npm install -g jest  

      # Step 4: Run backend tests
      - name: Run backend tests
        working-directory: ./backend
        run: npm test

      # Step 5: Install dependencies for the frontend
      - name: Install frontend dependencies
        working-directory: .
        run: npm install

      # Step 6: Run frontend tests
      - name: Run frontend tests
        working-directory: .
        run: npm test

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-and-test  # Run this job only if the build-and-test job succeeds

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy backend
      - name: Deploy backend
        run: |
          echo "Deploying backend..."
          # Add your backend deployment commands here (e.g., Docker, SSH, etc.)

      # Step 3: Deploy frontend
      - name: Deploy frontend
        run: |
          echo "Deploying frontend..."
          # Add your frontend deployment commands here (e.g., upload to S3, Netlify, etc.)